name: Continuous-Integration
on: [pull_request]

jobs:
  LicenseFinder:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Ruby and Install Gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Check Allowed Licenses
        run: |
          bundle exec license_finder permitted_licenses add "MIT" "Apache 2.0" "Simplified BSD" "Simplified BSD, ruby" "Apache 2.0, MIT" "New BSD" "Artistic-2.0, GPL-2.0+, MIT" "Brakeman Public Use License" "GPL-3.0+"
          bundle exec license_finder

  Brakeman:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Ruby and Install Gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Check Security Vulnerabilities
        run: |
          bundle exec brakeman

  BundlerAudit:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Ruby and Install Gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Verify Bundler
        run: |
          bundle exec bundle-audit update
          bundle exec bundle-audit check

  RSpec:
    runs-on: ubuntu-18.04
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
        ports: ['5432:5432']
        options:
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Ruby and Install Gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Build and Run Tests
        env:
          DATABASE_URL: postgres://postgres:@localhost:5432/test
          RAILS_ENV: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        run: |
          sudo apt-get -yqq install libpq-dev
          bundle exec rails db:prepare
          bundle exec rspec spec
